#server:
#  port: 8080

#rest:
#  basePath: /api

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    ddl-auto: create
#    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  jackson:
    default-property-inclusion: non_null
    mapper:
      default-view-inclusion: true
logging:
  level:
    ru.apex: INFO
    org:
      hibernate:
        type: INFO
      springframework.web.filter.CommonsRequestLoggingFilter: DEBUG